include: ["_pages"]

plugins:
 - jekyll-include-cache

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: air

markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  tools:
    output: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: true

title: "Denis Rossi"
title_separator: "|"
subtitle: "Backend engineer personal website"
masthead_title: "DR"
breadcrumbs: true

author: Denis Rossi

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-170207507-1"
    anonymize_ip: false # default

