include: ["_pages"]

markdown: kramdown

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

plugins:
 - jekyll-include-cache

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: air

masthead_title: "DR"
breadcrumbs: true

author: Denis Rossi

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  tools:
    output: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-170207507-1"
    anonymize_ip: false # default

