include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: air

masthead_title: "DR"
breadcrumbs: true

author: Denis Rossi

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
